---
title: "Week 1: Keynes's Life"
author: "Brian Weatherson"
date: "2023-08-07"
categories: [weekly handout]
abstract: "An overview of Keynes's life and work".
draft: true
---

John Maynard Keynes (1883-1946) was the most important economist of his generation, and arguably of any generation. But before he was an economist, he was a philosopher, and philosophical themes recur throughout his writings. This seminar is going to look at his early philosophical work, and some of the philosophical themes in his later economic and political work.

Keynes (or Maynard as he was primarily known) was the son of John Neville Keynes (1852-1949) and Florence Ada Keynes (1861-1958). His mother was a remarkable figure, who in the 1930s became Mayor of Cambridge, and who was probably very important to Keynes's education and character development. But his father is a little more interesting to our story. 

Neville Keynes, like Maynard, was both an economist and a philosopher. As we'll see through the course, this was not at all an uncommon combination during the late 19th and early 20th centuries, especially in England. Neville worked at Cambridge for most of his career, moving between academic and administrative roles. He published two notable books, a logic book in 1884, and an economics book in 1891. The logic book was the last great text of pre-Fregean logic, and gets cited throughout the 20th (and occasionally the 21st) centuries, especially by philosophers keen to present a more nuanced view of pre-Fregean logic than the caricatured version presented in standard histories.

So Maynard grew up around Cambridge. At the time, the field his father worked in was called Moral Sciences, and it covered what we'd now call economics, psychology, and philosophy, with philosophy being the largest part. And while his father was not exactly an academic star - he spent as much time working in university administration as working as a researcher, and his last major work came decades before his retirement - Maynard certainly grew up comfortable in academic settings.

Maynard's intense home education paid off when he won a scholarship to Eton. He doesn't seem to have developed a particularly close relationship to Eton. But Eton had a close connection to King's College, Cambridge. (If you go to Cambridge, you'll probably recognise it as the College with the fanciest chapel.) And as a graduate of Eton, Maynard won a place at King's, and stayed connected to King's for the rest of his life. His undergraduate degree was in mathematics. At the time Cambridge did a rank ordering of the mathematics graduates, the best being First Wrangler, the next Second Wrangler, and so on. Maynard finished 12th, which upset his parents, but seemed to satisfy him. 

After finishing his mathematics degree, he spent two more years around Cambridge. Officially he was preparing to take the civil service examination. Unofficially, he was kind of hanging around. But these years are particularly important to our story for two reasons. First, he spent a lot of this time sitting in on philosophy classes, and talking to philosophers, especially Moore and Russell. Second, he became a central figure in the Apostles.

The Apostles is (I believe to this day) a somewhat secretive discussion group primarily for undergraduates at Cambridge, consisting entirely of people who have been invited to join. They met (meet?) weekly to discuss some topic or other, usually something that at least had the pretence of being academic. At the time Maynard arrived, the club had two distinguishing characteristics. One was that it was heavily connected to philosophy. Sidgwick had been a lifelong active member, and Russell and Moore were heavily involved. (Wittgenstein had a complicated relationship to it, like he did to most things.) The other was that a very large proportion of the membership were gay. This apparently amused Russell, but Moore remained (if the stories can be believed) completely oblivious to the fact. Anyway, the friends Keynes made through the Apostles became many of his closest friends for life. And the mid-1900s Apostles became the core of the Bloomsbury group, the interwar group of writers, artists, and intellectuals who lived near the British Museum (i.e., in Bloomsbury). This group included (depending on whose definitions you read), Virginia and Leonard Woolf, Lytton Strachey, E. M. Forster, Roger Fry, Duncan Grant, and several other notables. And they basically were Keynes's main social and intellectual contacts until the 1930s.

Keynes took the civil service examination in 1906 and was disappointed to only come second. He'd been hoping to come first and get his choice of positions, which would have meant going to Treasury. Instead he came second, and had to settle for a position in the India Office. He never travelled to India, but did read and learn enough about it to eventually write a book, his first published book, on _Indian Currency and Finance_. I've never read it, and I'm not sure if there is anything of interest to us in it.

He didn't stay in the India office for long, returning to Cambridge in 1908. He was employed as a lecturer in economics, close to what we'd now call an adjunct, though his classes were very popular. (Note that at this stage he's taken no classes in economics, and is largely self-taught.) He was also working on something close to what we'd call a philosophy PhD, with the results being an early draft of the *Treatise on Probability*. This was very widely discussed at Cambridge, and went through extensive revisions over the drafts. Somehow (and I really don't understand how), he was appointed as editor of *The Economic Journal* in 1911, a position he held until near the end of his life. After publishing the Indian finance book in 1913 he was appointed to a Royal Commission on the Indian economy, which increased his fame in official London circles.

In 1914 he was back in Cambridge working again on the probability book. The legend (repeated in a lot of places, but I'm not sure if I believe it) is that when war broke out, Keynes was talking with Russell (about probability) on the main street of Cambridge when a motorcycle with a sidecar attached pulled up. It had been sent from London by Treasury officials desperate to get Keynes to London to help with wartime financing as urgently as possible. He jumped in the sidecar, and was a Treasury official for the next five years.

We don't need to spend much time on what he did at Treasury during the war, because while it is interesting to historians of public finance, it doesn't have a great deal of philosophical import. (At least on my understanding of the philosophy/non-philosophy boundary.) The main thing to know is that by the end of the war, Keynes was one of the most respected technocrats in London. So naturally he was part of the Treasury delegation to the Paris Peace Conference after the war, the conference that led to the Treaty of Versailles.

Keynes was not part of the delegation by the time the treaty was signed. He had resigned in protest at the harshness of the terms being imposed on Germany, and returned home to write a book setting out his objections. The book, published in November 1919, was called _The Economic Consequences of the Peace_, and is a devastating attack on the treaty and on the people who put it together.

I haven't set any of the Versailles book in the reading for this class, because ultimately I couldn't find a part that seemed suitable for a weekly seminar. I do think it should be treated as a work in political philosophy; very applied political philosophy to be sure, but still philosophy. It's hard to read the first few pages and not see a vivid moral theory that's illuminating the whole work. But that theory is stated more than defended, and the practical issues are not exactly our practical issues. Still, I very much recommend reading it, especially the first few chapters, before you get to all the tables about the details of this or that part of the reparations. It's an astounding piece of writing, one that amazed Keynes's literary friends, who had no idea that he was in their league as a writer.

In one of the most quoted passages of the book, Keynes describes what life was life was like for the upper-middle classes of England before the war. We could definitely question how realistic Keynes was being when he said this state of affairs was attainable for many people, or how good a state of affairs it was. But I think it's really interesting, and so evocative of a certain way of life. (Note the absence of passports as one aspect of the world Keynes so desperately wants to bring back.)

> What an extraordinary episode in the economic progress of man that age was which came to an end in August, 1914! The greater part of the population, it is true, worked hard and lived at a low standard of comfort, yet were, to all appearances, reasonably contented with this lot. But escape was possible, for any man of capacity or character at all exceeding the average, into the middle and upper classes, for whom life offered, at a low cost and with the least trouble, conveniences, comforts, and amenities beyond the compass of the richest and most powerful monarchs of other ages. The inhabitant of London could order by telephone, sipping his morning tea in bed, the various products of the whole earth, in such quantity as he might see fit, and reasonably expect their early delivery upon his doorstep; he could at the same moment and by the same means adventure his wealth in the natural resources and new enterprises of any quarter of the world, and share, without exertion or even trouble, in their prospective fruits and advantages; or he could decide to couple the security of his fortunes with the good faith of the townspeople of any substantial municipality in any continent that fancy or information might recommend. He could secure forthwith, if he wished it, cheap and comfortable means of transit to any country or climate without passport or other formality, could despatch his servant to the neighbouring office of a bank for such supply of the precious metals as might seem convenient, and could then proceed abroad to foreign quarters, without knowledge of their religion, language, or customs, bearing coined wealth upon his person, and would consider himself greatly aggrieved and much surprised at the least interference. But, most important of all, he regarded this state of affairs as normal, certain, and permanent, except in the direction of further improvement, and any deviation from it as aberrant, scandalous, and avoidable. The projects and politics of militarism and imperialism, of racial and cultural rivalries, of monopolies, restrictions, and exclusion, which were to play the serpent to this paradise, were little more than the amusements of his daily newspaper, and appeared to exercise almost no influence at all on the ordinary course of social and economic life, the internationalisation of which was nearly complete in practice.

The book has two central claims. One is that the demands of the treaty will be literally impossible to meet, unless perhaps they are met by literally starving the German people. The other is that this will all lead to another war. And while there definitely was another war, both claims have been controversial. It's been argued that Keynes underestimated the German economy. The most ironic version of this argument is that the economic theory of this book is too indebted to the flawed economic theories from the turn of the century; if one analysed the situation using a correct theory, like that in Keynes's _General Theory_, Germany's situation would not look as dire. It's also been argued that the book was a self-fulfilling prophecy. What led to the next war was not the Versailles Treaty, but the impression that the Treaty was unfair. And that impression was as much due to Keynes's book as to the Treaty itself.

That last claim might seem absurd until you realise how big a deal the book was. It sold 100,000 copies, was translated into 12 languages, and its view of the peace treaty, especially the phrase that it was a Carthaginian Peace, became commonplace throughout the world. It contributed, somewhat unintentionally, to America's refusal to join the League of Nations. And while it led to Keynes becoming famous throughout the world, it meant that he was well and truly out of favour in official London.

That last point is relevant to our story because the next few years would be amongst the most prolific in Keynes's already prolific writing career. In quick succession he published three books. In 1921 he finally published the long gestating _Treatise on Probability_. In 1922 he published a sequel to the Versailles book, _A Revision of the Treaty_, which had a much smaller impact than its prequel. And in 1923 he published _A Tract on Monetary Reform_.
The _Tract_ grew out of some columns he wrote for the _Guardian_, who sent him to a conference on post-war reconstruction as a columnist. On the one hand, being a columnist for a national newspaper means one is still somewhat part of the national conversation. Still, it's a long way from the official standing Keynes had had before the publication of his Versailles book.

The _Tract_, and some of the writings around that time, are interesting in part because they address a question that has recently taken on some practical significance. Assume we think, as Keynes will later come to deny, that something like price stability is an important object of government policy. And assume also that prices have recently risen sharply. What should the government now aim at? One option is to try to stabilise prices at this new higher level. Another is to return prices to where they were, i.e., to have a bout of deflation to ensure that long-term prices are stable. As far as I know, the latter view has no serious proponents nowadays. But it was taken seriously when Keynes was writing. Indeed, it seems to have been behind some of the disastrous decisions Churchill made as Chancellor of the Exchequer (the UK equivalent of Treasury Secretary) during the 1920s. Keynes, though not yet as relaxed about inflation as he would be in his later career, thought this was a terrible idea, and that whatever evils inflation might have, deflation was so much worse that we'd have to just live with this new higher price level. On this point, conventional wisdom now entirely agrees with Keynes. Milton Friedman later said that he liked this book very much. If you don't know Friedman's work, it's probably too much of a digression to go into why this might be a bit surprising, but it is indicative both of how much more centrist Keynes was in the 1920s than the 1930s, and how much political debates have shifted over the last 100 years.

The early 1920s also saw a major change to Keynes's personal life: he got married. This was particularly surprising since as far as we can tell, he had had exclusively male romantic partners up until then. But he fell in love with a Russian ballerina, Lydia Lopokova. This led to something of a falling out with Keynes's Bloomsbury friends, some of whom didn't take Lydia seriously, and preferred not to have her around intellectual conversations. But Keynes was devoted to her and, again as best we can tell, was entirely faithful during their marriage (if not during their courtship). He was a dedicated supporter of the arts, and this included building a theatre in Cambridge, in part for Lydia to have somewhere to perform. They didn't have any children. 

The rest of the 1920s was Keynes's most prolific period for public writing. This was helped in part by his leading a consortium that bought _The Nation and Athaneum_ in 1923, which meant he had easy access to its pages. He was encouraged to hire T. S. Eliot as literary editor, but the two of them didn't get along, so the job went to Leonard Woolf. The financial stability of this job helped the Woolfs get the Hogarth Press running, which soon published Virginia Woolf's most famous works. One other amusing aside about this time. During the 1926 General Strike, Keynes and Woolf disagreed about what the magazine should do. Keynes wanted to run articles supporting the strikers; Woolf wanted to go on strike in solidarity with them. Keynes was officially the boss, but Woolf had possession of the printing press; there was no strike edition.

There are two really notable pieces to comes out of this flurry of public writing. In 1929, as part of the Liberal election campaign, he and Hubert Henderson (an important economist and another of his employees at _The Nation_) wrote _Can Lloyd George Do It?_. This was a defence of David Lloyd George's New Deal-like economic plans that he was taking to the 1929 election. Given the harshness of Keynes's tone towards Lloyd George a decade earlier, it was remarkable that the two could become close collaborators. But it made little difference; the Liberals did poorly at the 1929 election, and the result was the first ever Labor government. The other, which we'll talk about more next week, was his essay _Economic Possibilities for our Grandchildren_. This was one of the last things he published in _The Nation_ before selling/shutting it, as in 1931 it merged with the moderate Labour publication _The New Statesman_, and Keynes retained some influence with the new journal. (And published some interesting work in it, though not enough to stop the magazine's lurch to the Stalinist left.)

In 1930 Keynes also published what was intended at the time to be his magnum opus, the two volume _Treatise on Money_. This is a difficult book for several reasons. It's not that difficult on a page-by-page basis, though some of the terminology takes some getting used to. Indeed some of the passages contain some of Keynes's best academic writing. It's rather that seeing how the whole fits together can be a challenge. Keynes himself is said to have thought the work an "artistic failure", and attributed its difficult structure to the fact that he changed his mind too often while writing it.

After this, Keynes set to work on his real magnum opus, _The General Theory of Employment, Interest and Money_. As the Great Depression hit, he was still writing in public to encourage greater public works programs. He was strongly in favour of the New Deal as a whole, though he disapproved of some parts. His loud support for it led to a meeting with President Roosevelt, though probably not much came of it. But it did mean that he was thinking more and more about America, and in some ways _The General Theory_ is more about America than about Britain. It's notable, for example, that it contains relatively little discussion of foreign trade, or even of currency movements. In economists' terms, it's more like a discussion of a closed economy than an open one. Keynes spent more time in Cambridge over these years, developing a tight circle of admirers and collaborators. These included Richard Kahn, the developer of the concept of the multiplier, and Joan Robinson, among other things the great theorist of imperfect competition. These younger economists played important roles in developing the _General Theory_. So did Keynes's sometimes acrimonious letters with economists of his generation who opposed his views. (Many of these letters have been published, and they are a helpful resource in understanding _The General Theory_ and its development.)

_The General Theory_ came out in February 1936 and it was, by academic standards, a publishing sensation. Keynes had insisted it come out in paperback, and affordably priced, and sold well. Among academics, it became the most important work in economics for generations. Google Scholar today has it at 58000 citations (though these are wrongly attributed to a 1937 article that we'll get to later). The book develops a model of the economy where decisions whether to invest are the driving force behind the level of employment we see, as opposed to models that prioritise either the wages demanded by workers (as in simple supply-demand models of employment), and to models where decisions to save were the driving force (as Keynes himself had to an extent believed when he was younger). The short term political upshot of this model was that deficit-financed spending, especially on infrastructure, was a good way to get out of slumps like we saw in the 1930s. As with Keynes's earlier arguments against trying to undo inflations, this has again acquired the status of something like conventional wisdom. The longer term political upshots of the model were, well that's a more contentious issue. Keynes himself says at the end of the book:

> I conceive, therefore, that a somewhat comprehensive socialisation of investment will prove the only means of securing an approximation to full employment; though this need not exclude all manner of compromises and of devices by which public authority will co-operate with private initiative.

And this is in a paragraph that starts "In some other respects the foregoing theory is moderately conservative in its implications"! I don't think we'll really get into it in this course, but exactly what the ideal state would be for Keynes, and how it relates to other grand ideal political theories, especially other ones that call for "comprehensive socialisation of investment", is an _interesting_ question.

Keynes wrote a number of journal articles immediately after the publication of the _General Theory_ responding to critics and spelling out the theory some more. The most notable of these for our purposes is the confusingly named 1937 article in the _Quarterly Journal of Economics_ called "The General Theory of Employment". (This is the article Google Scholar assigns all the citations to.) Among other things, this article spells out in a bit more detail some of the connections between the _Treatise on Probability_ and the _General Theory_, though exactly how to interpret this connection, and this article, is a matter of some scholarly dispute. (I tried to join this dispute as a grad student, but I didn't have luck getting early things published, and soon gave up. But I still have _strong views_ about some of the participants in it.)

Then, in late 1937, Keynes had a massive heart attack. It didn't kill him, but it did knock him out of serious work for nearly two years. By the time he was relatively recovered (he never really fully recovered), the world had changed completely. World War II had started, and all the challenges of wartime meant that the challenges of how to handle a slump stopped being the centre of attention. Keynes died in 1946 without ever really returning to his more theoretical work, so we don't have as much as we'd like of follow-ups to the _General Theory_ as we'd like.

With a war on, official Britain again turned to Keynes to figure out what to do with its finances. In 1940 he published an interesting pamphlet called _How to Pay for the War_, which dealt with how Keynes thought wartime inflation and shortages should be managed. The same year he and Pierro Sraffa (another economist we could do a seminar about) wrote a paper arguing that David Hume was the author of the "Abstract" of the _Treatise on Human Nature_. I gather they were largely convincing, and this is now usually attributed to Hume. He worked with his friend William Beveridge on a report into post-war welfare systems. This report, which became popularly known as The Beveridge Report, was very influential on the post-war Labour government, which established the comprehensive welfare state. And then Keynes set seriously to work on the negotiations with the Allies on what post-war international finance will look like. This gets both well outside my expertise, and well outside what most people would consider philosophy work, and we're not going to cover it at all in this course. Suffice to note that Keynes spent the latter half of the war shuttling back and forth between the US and UK - not a minor exercise with U-Boats everywhere. And he was at the centre of all the negotations that established the post-war financial institutions, including the Bretton Woods system of managed currencies, the International Monetary Fund, and the World Bank. But that didn't mean he designed these things; in fact he was on the losing side of many of the debates and negotiations. America, not Britain, was going to call the shots after the war, and there was little that a British diplomat could do about it, even if they were the greatest economist of the age.

Keynes had never been in the best of health. He didn't exercise much, he smoked heavily, and medical care wasn't as good then as it is now. At times during the war, and especially during his travel around the US from one negotation to another, he came perilously close to death. So it wasn't a surprise that he died soon after the war, in 1946. He was survived by his wife, who lived until the late 1970s, and both managed and guarded Keynes's intellectual legacy.

I've listed these in the narrative, but it's worthwhile having a list of Keynes's books in one place:

- _Indian Currency and Finance_ (1913)
- _The Economic Consequences of the Peace_ (1919)
- _Treatise on Probability_ (1921)
- _A Revision of the Treaty_ (1922)
- _A Tract on Monetary Reform_ (1923)
- _Treatise on Money_ 2 vols (1930)
- _The General Theory of Employment, Interest and Money (1936)

For modern academics, you'd also expect a list of the important journal articles. But despite being the editor of _The Economic Journal_ for more than three decades, Keynes didn't have that many famous journal articles. The 1937 article we'll look at is probably the most famous. What he did have were public writings, letters, official reports, speeches, and obituaries. Two 'greatest hits' volumes of these writings were collected in his lifetime, _Essays in Persuasion_ and _Essays in Biography_. Just to confuse everyone, these have been frequently reissued with extra pieces added to them, though I think we've just about standardised on the versions in the (Cambridge University Press issued) Collected Works.

In 1949 his estate issued a small book, _Two Memoirs_, containing two pieces that he'd held for posthumous publication. One of these, _My Early Beliefs_, we will discuss in detail next week. It goes into great detail about Keynes's philosophical education;the early beliefs were largely the result of reading and talking about Moore's _Principia Ethica_. But it was written in 1938, while Keynes was recovering from the heart attack, and 35 years after some of the events described, and some have questioned its accuracy. I think it's delightful, and fascinating, and I'll have much more to say about it going forward. The other paper _Melchior, a Defeated Enemy_, is a quite remarkable memoir of his time at the Peace Conference. It contains a confession to a bit of light treason (not quite stated as such), and possibly to other crimes, some sweeping generalisations about other nationalities and regions, and some of the best writing I've ever seen from an academic. It should come with all the content warnings, and did even in 1949, but you should also read it.