# Nothing More Powerful than Ideas

Let's start at the end, with the remarkable ending of the book. It's possibly the most quoted part of the book, joining the _Tractatus_ and Hume's _Enquiry_ perhaps in books whose endings are among the most memorable things about them.

Keynes gives a rather grandiose claim about the role of "economic and political philosophers" in history. They, we?, turn out to be the most important people in the world. Even if our ideas only end up getting implemented by thugs with guns, just which direction the thuggery takes is, according to Keynes, determined by the philosophers. It's a big role!

Is he correct about this? The first thing to think about might be the madmen in authority at the time Keynes was writing. It wasn't a great time for European political leadership: Stalin in Russia, Hitler in Germany^[We could perhaps talk about the preface to the German edition of the _General Theory_, which is notorious for not being quite as anti-Nazi as one might hope.], Mussolini in Italy, Franco in Spain. Are they just following recent academic scribblers? 

Franco doesn't look like a great case for Keynes. He's just following a fairly well established playbook of balancing the power of the powerful groups he cared about: the army, the church, and big business. If there's a grand theory there beyond look after one's own, I'm not sure what it is.

Hitler and Mussolini are a bit more interesting. How much is Keynes thinking that Nietzsche and/or Pareto (or similar figures) are responsible for what they are doing? Or is he even thinking of Heidegger here; that's unlikely given the timeline. But there's plausibly a case that the distinct way that Hitler and/or Mussolini ruled is a function of various theories.^[Mussolini has the added complication that, like every military leader from Italy, everything harkens back to the Roman Empire. But, Keynes might say, it's always a version of Rome; what matters isn't what Caeser or Trajan did, but what Mussolini and his friends were taught they did.]

But Stalin might be the most interesting case. On the one hand, it's hard not to read this passage as a swipe at the Marxist theory of history. The idea that 'vested interests' determine history is a (crude, uncharitable) summary of what Marx thought. And Stalin was obviously the only Marxist among the four I mentioned.

Now on the one hand, Stalin was in a sense the least doctrinaire of the Bolsheviks, indeed almost of any of the left-wing leaders in 1917. It's not clear how much he even *read* Marx. He certainly wasn't going to be like the Mensheviks and put off the revolution because history said it couldn't happen yet. He was even less likely to bother with writing his own treatise on how Marx had to be updated a la Trotsky. So does that tell against Keynes?

I don't think it does. Stalin was a very doctrinaire leader, even more so than Lenin ever was. Collectivisation wasn't Stalin's idea, but it very much became his policy. I don't think Lenin did much collectivisation at all. And Stalin kept at it, well after it had become clear that it was a catastrophic failure. I don't even think it really satisfied the material interests of the group Stalin allegedly represented. But he'd been a Bolshevik for as long as he could remember, and this was Bolshevik policy, and he was determined to put it into practice.

It's also worth noting the notable failures of Marxist theories in predicting what would happen after World War I. These theories make some fairly clear predictions. First, revolution should come first to the most developed countries. Second, there needs to be a bourgeoisie revolution (a la 1789) before there is a proletarian revolution (a la 1792 or 1871). None of that happened. The German revolution failed almost at inception. The bourgeoisie revolution in Russia was basically a failure, but the proletarian revolution happened anyway.

That said, if there is a problem for Keynes's theory of history it might come from the leader he most admired at this time: FDR. It's obviously not true that the New Deal came from economic and political philosophers that FDR read growing up. No one was advocating that then! Keynes himself wasn't advocating anything like it.

Indeed, there's some tension between the picture we get in chapter 23 and the one we get at the end of 24. In chapter 23 one of the running themes is that the politicians kind of know what they are doing. Not in any deep sense of course; their theories about why things work are typically off in every possible respect. But they do, as a group, have an intuitive sense of what needed to be done. And the plans are at least directionally correct.

The gold standard era politicians who cared a lot about the balance of trade were, thinks Keynes, basically doing the right thing given the constraints they had to work with.^[That's not because there's anything special about the balance of trade. But because of the details of how the gold standard worked, a better balance of trade meant better, i.e., lower, interest rates. And that's what really mattered.] Those politicians weren't just following the ravings of an academic scribbler some years back. All the academic scribblers were united in their opposition to such a policy.

So while I'm somewhat sympathetic to Keynes's views about the madmen in authority, and very sympathetic to taking shots at the Marxist theory of history, for better or worse I don't think it's our ideas that ultimately rule the world. Sometimes it's the animal cunning of the politicians.

# The Classical Theory

I suspect everyone here knows this as well as I do, but I wanted to set out what I take to be the 'classical' theory of unemployment; the one that Keynes is responding to in chapter 2. (And, frankly, the rest of the book.)

Start with the theory about the market for some particular good. Let's use milk as our example. Here's the simple textbook version. 

Start by holding fixed the income of everyone in the community, and the price of all other goods in the economy. Given those facts, there is an amount of milk each person would buy for each possible price of milk. Summing these up, we get the amount of milk that the community will buy for each possible price of milk. That is, there is a function D from prices to quantities such that D(p) = q means that at price p, we'll collectively buy quantity q of milk. And D is downward-sloping; at higher prices we buy other things instead.

There is a similar function S(p) = q from prices of milk to the amount of milk supplied. And this is upward sloping. As the price of milk rises, more people get into the dairy business, and more milk is supplied. But as the price falls, farms go bankrupt, and the supply shrinks.

So that means that there is a unique point where D(p) = S(p). And that price is going to be the price of milk, and the quantity of milk bought/sold is D(p) = S(p).

The classical theory says that labour is like this as well. In this case the price is wages, so let's write it as w. Again, there is a D function and an S function, though one thing to note already is that who determines D and S is flipped from the usual case. D is a function of what business does; S is a function of what normal people do. That's the other way around to normal, and I guess this matters.

Anyway, D(w) is the amount of labour demanded (by businesses) at wage w. The higher w is, the less labour they'll demand. If wages are high, you stop opening your restaurant at low traffic times, for example.^[That's happened a bit in Ann Arbor recently.] If wages are low, you'll employ people for things that might not be profitable in normal times.^[Think of all those Great Recession era delivery services that started up.] So D slopes down, just like the normal case. And, says the classical theory, S slopes up. Once w gets low enough, some people will decide that it's not worth getting out of bed for less than $10,000, and stay in bed. So we've got the same conditions that are met in the milk case. We have two functions with opposite slopes, so they will have a unique intersection where D(w) = S(w). That value of w will be the wage level, and D(w) will be the amount of labour demanded. If it's less than the size of the employable population, there will be unemployment. But note that this could all be fixed with a shift in S; if people weren't so reluctant to work for lower wages, we could have a higher employment equilibrium.

# Problems with the Classical Theory

Start with why this is a less than optimal theory of the price of milk. The theory is what's called a **partial** equilibrium theory. It doesn't try and balance all the forces in the economy; just the forces that directly affect the price of milk. But this leaves out all sorts of complications that could, in principle, be important.^[General equilibrium theory tries to solve for all of these forces at once, and given some truly heroic assumptions you can prove the existence of a unique general solution. But the assumptions are really rather absurd, and unlike partial equilibrium theory, there is no particular reason to think that having the assumptions be nearly satisfied will make the result nearly correct.] In particular, and for our interest, it leaves out complications caused by the existence of complementary goods, and possible macro effects of the particular market.

Complementary goods are a ubiquitous feature of our lives. They are goods that have more value if other goods are available. Gasoline is a complement to cars, for example. Or, to bring it back to milk, milk and corn flakes are complementary. If the price of corn flakes falls, demand for milk will go up. So if the solution to the equation for milk had a material effect on the price of corn flakes (e.g., because milk was also used as an input to corn flakes), the partial equilibrium would really not be a general equilibrium.

The weird things that happen with complementary goods are incredibly important parts of the current economy. I write these notes using two main bits of software, VS Code and RStudio. Both of these are provided, for free, by for profit companies. And they are provided because they are complements to other goods those companies provide. In RStudio's case, at least as I understand the business model, the complementary good is paid customer support for RStudio. It's not exactly trivial to do a partial equilibrium analysis of a product like that!

The other issue is macro-economic consequences. I guess these days no one thinks this is a particularly realistic case, but when I was a student we were taught to worry about so-called Giffin goods. Consider the following just-so story about the market for some basic food in a society that is just above the subsistence line. If the price of that basic food goes up, demand for it might go **up**. The reason is that people who were just above subsistence level, and hence able to afford alternatives to the basic food, will be thrust back into a state where they can afford nothing but the basic food. This does seem possible in theory, though I gather no one thinks it has ever occurred in practice. But what matters to us is the general possibility; the resolution of forces within some market might have wide-ranging effects.

Both of these things matter, thinks Keynes, in the labour market. 

Labour is a complement to capital. In Keynes's model, simply employing people is actually not something commonly done. Rather, people _start businesses_, and a business requires labour and capital. Ultimately, Keynes's explanation of the market for labour, which is the thing in the title of the book, is that it is kind of a side-effect of the market for capital, i.e., investment goods. Now we might worry somewhat about this. Sometimes unemployment goes down because of new investments; e.g., a factory gets built. But sometimes unemployment goes up because of new investments. That happens at a trivial level with things like ATMs, but it happened at a much larger scale in agriculture. I'm worried these things affect Keynes's story.

More importantly, labour has macro-economic effects. Labour is such a big part of the economy that changes in wages mean changes in the overall price level, and in the overall demand for goods.^[Strictly speaking this is true for every good, but it's pretty much ignorable in the case of corn flakes, and even milk.] In chapter 2, we get one direction of this. If the wage goes down, prices will fall, but that might mean the _real_ wage hasn't changed much at all. Keynes is a bit slippery here, and doesn't work out whether the magnitudes really work. And ultimately I'm not sure that what he says in chapter 2 is really what he thinks. The big problem with a cut in wages is that it will lead to less demand, which leads to less investment, which means fewer things for labour to complement, which means possibly a _fall_ in the demand for labour. But that's getting ahead of ourselves. For now the worry is that a change in wages will lead to a change in demand for good produced by workers (what Keynes calls wage-goods), and that will change the demand curve for labour. So there is no guarantee that there can be an equilibrium.

# Keynes's Positive Theory

This gets more complicated, and the exegesis is more controversial. But here I think is the view in the very broadest outline.

Labour is a compliment to capital. Ultimately, the demand for labour is a by-product of the demand for investment. And the demand for investment is determined by two things:

1. How much investors expect speculative investments to yield.
2. How much investors can get from things other than investments, in particular from money.

And so we get a lot of chapters in the middle of the book on these two factors, on what determines the expectation of investment yield, and on what determines the rate of interest. Both of these are, I think, philosophically interesting, because they both connect to the somewhat distinctive way in which Keynes is thinking about rational choice.

That said, Keynes doesn't reject the classical view quite as much as one might perhaps have expected. He does think that in a slump, solving the problem will require a fall in real wages. This isn't because he believes in a supply-demand story about labour. Rather, it's because (I think) lower real wages leads to higher expected investment return, leads to higher investment, leads to more jobs.

So why don't we end back with the policy prescription of the classical view: the solution to a slump is to cut wages? There are a few reasons, but the biggest is that word **real**. Keynes thinks that you need to have a real wage cut to solve the problem, and cutting money wages won't do the trick.

But here we get into one of the more common interpretations, I think misinterpretations, of Keynes. One way a lot of economists (mostly but not exclusive right-leaning) read Keynes is as giving a story of what an economy with _sticky wages_ looks like. Some of them agree (especially the not so right-leaning ones) that he's given a very good diagnosis of what a sticky wage economy looks like. But, they say, this shows that the title of the book is completely misleading. He hasn't analysed the general case at all, just the weird special case where wages are sticky.

Now one thing to note immediately is that wages very much are sticky at least in the short term. I don't think I've had my (nominal) pay change during the academic year once in my career. You make a deal in dollars, and that deal is paid out in dollars. It's not that special a case.

But note that the more right-leaning economists who think this see sticky wages as a double failing.

First, it's a failing on the part of the workers who don't realise that inflation is the same thing as a wage cut. These economists think that at best Keynes is offering governments a one-time trick. Do a quick inflation, no one will notice that their real wages are cut, and it will be just like the prescription we wanted. But you can't fool people the same way twice. If you keep doing this, workers will start demanding things like Cost of Living Allowances, i.e., automatic inflation adjustments. And then it will all fail.^[To be totally clear about this, the story continues by claiming this is _exactly_ what happened in the 1970s, so it explains why Keynesian economics seemed to work for a while, but also why it failed.]

Second, it's a failing on the part of the government. If you'd just be tough enough with the unions, like Thatcher with the miners or Reagan with the air-traffic controllers, you break union power, and you don't need sticky wages any more.

I think this is a complete misreading of what Keynes is up to in chapter two.

# Rationality and Sticky Wages

There are two arguments Keynes gives for why sticky wages are a good thing. The second^[And, to be clear, the one he says is more important, even though I'm spending less time on it because it's less philosophically relevant] is that if wages were too responsive to price moves, we'd never get to equilibrium. Every minor slump would lead to a race to the bottom to find a point where wages were low enough; every boom would lead to an out-of-control wage-price spiral.

The first is more interesting to us. Keynes makes the workers sound like folks playing a Schelling-style coordination game.^[If not everyone knows what this is, I'll stop and explain, because it's a really useful concept.] If there's a slump, what's best for workers collectively is that real wages are slightly cut. But for any individual worker, having their wages cut by more than other wages are cut is unnecessary. So there is a coordination problem. We need to find a way to cut everyone's real wages, no more nor less than is needed to get out of the slump, and to do so in a way that shares the pain as evenly as possible.^[Actually the individual workers need not care about fairness; all they need to care about is that their probability of losing their job is low, and that their wages are as high as possible given the first constraint.] There are a bunch of ways to bring this about. If we need to cut real wages by 5%, any combination of cutting nominal wages by x%, and having y% inflation, where x+y=5, will do it. If everyone else would agree to an x% nominal cut, it's in the interest of these workers to agree to it as well. But if the aim is to find a value of x that we can all agree on, the natural value, the focal point as Schelling might have put it, is 0. The simplest equilibrium of the game the workers, collectively, are playing is that nominal wages stay exactly where they are: no one gets a (nominal) wage cut, but no one gets compensated for the inflation that's happening.

What I really want to stress is that if this is a coordination game, this is completely rational behaviour. This is not a bounded rationality model; it's a model where the relevant kind of rationality is game-theoretic, not decision-theoretic.

# Keynesian Rationality

Simplifying only a little, Keynes thinks the model of rational choice used in standard economic models is too impoverished in three respects. It doesn't allow for:

1. Planning
2. Coordination
3. Sensitivty to uncertainty

The first two are what you get if you move from decision theory to game theory. The third is more distinctively Keynesian.

In the standard economic models^[That is, the ones we are using when we tell those simple stories about milk], our consumer has an income constraint, and a bunch of consumption goods they can purchase. There isn't an obvious place for planning, and especially for saving. Now we can complicate the models only a little^[And, to be sure, you start getting these complications by 200- or 300-level courses] to allow for shifting consumption over time. 

But there is an important catch. In one sense, the way we defer consumption to the future is by buying a very special kind of good: money. Money is a special kind of good because it's supply does not look anything like the supply of milk, or corn flakes, or really anything else. And one thread in the book is going to be the important features of this market.

Planning is going to matter in another context as well. Let's say the price of corn flakes falls. Do you buy more corn flakes? Well, maybe not. If the price fall is evidence that the price is going to fall again soon, then maybe the price fall will _decrease_ demand, because people (who are not stupid) will see that an even better deal is just around the corner. That's maybe not such a big deal for corn flakes, but it is going to be very important in explaining the market for investment goods, which as I've said a few times, is the central market.

Coordination is what we've just seen. In the simple supply-demand models, there are infinitely many agents, and coordinating with any finite subset of them makes no economic difference. That's, er, not the world we actually live in. And if my reading of chapter 2 is right, Keynes takes these coordination effects really seriously.

Finally, though it doesn't come up yet, Keynes is going to want a theory of rationality that is sensitive to the risk/uncertainty distinction. Exactly how the risk/uncertainty distinction matters is a question that's very hard to get clear on, and gets into the murkiest exegetical waters. But it's something we'll talk a lot about the next two weeks.



# Why Markets?

In chapter 24 we get, by my count, three different arguments for wanting an economy (and even society) where markets play a key role.

First, there is a very standard liberal style argument about the relationship between markets and freedom/autonomy. Some of these paragraphs look like they could have been written by Mill, or Friedman, or Hayek.

Second, there is the closely related argument that totalitarian systems are really drab. Everything looks the same as everything else, and there is no place for 'fancy'. As arguments go, we should reject Bolshevism because the buildings are ugly and the music is boring isn't the most high-minded, but I think he's got a point.^[I'm using 'Bolshevism' as opposed to 'Marxism', or 'communism', let alone 'socialism', because the opponent here really is the very specific system being implemented in the Soviet Union. And if I use any other term I'd have to get into interpretative disputes about whether northern European social democratic movements, which Keynes is very friendly to, are excluded from those terms.]

Third, there is the argument that people who are really keen on playing with markets, who are really obsessed with money are, to put it bluntly, kind of psychopaths. If you don't have markets, they'll start playing with something else. And that will be worse.^[The premise that the something else will be worse is, I guess, somewhat questionable, given the downside effects of pollution, money laundering, etc.]

Note that while Keynes is largely pro-market, he is anti-capitalist. What he objects to is the central role that holders of capital play in the then operative system. In his ideal world, capital is so plentiful that it isn't a constraint. It's worth spending a bit of time I think on what an anti-capitalist, pro-market system might look like.

Think for a bit about what's happened to the music business over the last half century. Fifty years ago, you really needed capital to play in the music business, and the people who had it served as gatekeepers. Home recordings were dire, so you had to record in a studio, and these were expensive. And no one had ability to press vinyl records at home, so you have to pay one of the people who had a machine. And then you needed some way to distribute those (simultaneously heavy and fragile) across the country, probably to a retail store that was part of a chain. The distribution is typically managed by a label, and getting more than a handful of people to hear your music requires getting signed to one. But you can't start your own if you expect to succeed; they are big businesses.^[One of the biggest is even called Capitol.] There are so many steps, and at every one of them you have to pay a fee. Indeed, you have to find someone who is willing to take your money.

We can imagine a world that has none of those things. Technology has meant home recordings are easier. And those recordings are distributable in a way that does not require moving heavy or fragile things around. So far so good.

Imagine a world where there was a site like Bandcamp, but it was run at cost by a state or state-adjacent agency.^[I'm using 'state-adjacent' here for things like USPS and UM that aren't part of the civil service, but aren't private actors either.] On this site people could upload whatever music they wanted, and charge whatever they wanted for it, and they got a large percentage of that money, with the site doing no more than covering its costs of hosting and payments processing.

That's almost, but not quite, Keynes's vision. His actual vision is that the returns on capital are so low that someone will have been inspired to set up Bandcamp-with-low-fees to get more than the pittance they can earn in interest. Competition among people looking for places to invest will drive the value of capital goods down, and the result will be that there is a market for things made by actual producers (e.g., musicians), and the infrastructure for it will be provided at really minimal cost.

This is the nirvana that we were supposed to get with low interest rates. And two decades ago I might have argued that it was a plausible story. But we had the low interest rate economy, and it didn't work that way. So let's end with why it didn't.

# Euthanasia of the Rentier

Anglophone economics, indeed European economics, in a modern sense starts with Adam Smith. And Smith, like most economists of his time, was really opposed to rent. Businessmen have their flaws, to be sure, but they are at least trying to provide goods and services. The landed aristocracy are just taking a cut. Developing economic theory is part of a broad campaign against these rent-seekers.^[Bankrupting the French monarchy and bringing on the French Revolution is also part of this campaign, though maybe not the most successful part.]

A rentier is a person living off their rents in general; not necessarily rent of land or buildings, but possibly rent of capital goods. And Keynes is saying that they are just as problematic as the early moderns thought the landed aristocracy were. Keynes is on the side of entrepreneurs against the people who want to charge them fees in order to make businesses happen. It's just like Smith, except with 

You can see the mode 
